service: serverless-instagram-no-resize

# lock us to a pre-2.0 (not yet released) version of the serverless framework to protect us from breaking changes
frameworkVersion: ">=1.16.0 <2.0.0"

plugins:
  - serverless-python-requirements

custom:
    config: ${file(config.json)}

provider:
  name: aws
  region: us-east-1
  runtime: python3.6
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::${self:custom.config.UPLOAD_BUCKET}
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::${self:custom.config.UPLOAD_BUCKET}/*
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.config.METADATA_TABLE}"

package:
  individually: true
  exclude:
    - '*/**'

functions:
  auth:
    handler: authorizer.handler
    environment:
      AUTH0_SECRET: ${self:custom.config.AUTH0_SECRET}
      AUTH0_AUDIENCE: ${self:custom.config.AUTH0_AUDIENCE}
    package:
      include:
        - authorizer.py

  signurl:
    handler: generate_signed_url.handler
    environment:
      UPLOAD_BUCKET: ${self:custom.config.UPLOAD_BUCKET}
    package:
      include:
        - common/*
        - generate_signed_url.py
    events:
      - http:
          path: /get_signed_url
          cors: true
          method: get
          authorizer: auth
  metadata:
    handler: add_metadata.handler
    environment:
        METADATA_TABLE: ${self:custom.config.METADATA_TABLE}
    package:
      include:
        - add_metadata.py
  list:
    handler: list_metadata.handler
    environment:
        METADATA_TABLE: ${self:custom.config.METADATA_TABLE}
    package:
      include:
        - common/*
        - list_metadata.py
    events:
      - http:
          path: /list
          method: get
          cors: true

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      DependsOn:
        - PushMetadataPermissionUploadBucket
      Properties:
        BucketName: ${self:custom.config.UPLOAD_BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedMethods:
                - "GET"
                - "PUT"
              AllowedHeaders:
                - "*"
              MaxAge: 3000
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: "s3:ObjectCreated:*"
              Function:
                "Fn::GetAtt": [ MetadataLambdaFunction, Arn ]

    PushMetadataPermissionUploadBucket:
      DependsOn:
        - MetadataLambdaFunction
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          "Fn::GetAtt": [ MetadataLambdaFunction, Arn ]
        Action: "lambda:InvokeFunction"
        Principal: "s3.amazonaws.com"
        SourceArn: "arn:aws:s3:::${self:custom.config.UPLOAD_BUCKET}"

    MetadataTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: image
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        KeySchema:
          - AttributeName: image
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.config.METADATA_TABLE}
